# Generated by Django 2.2.4 on 2019-11-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('sector', models.CharField(choices=[('1', 'Agricultura; plantaciones, otros sectores rurales.'), ('2', 'Alimentación; bebidas; tabaco.'), ('3', 'Comercio.'), ('4', 'Construcción.'), ('5', 'Educación.'), ('6', 'Fabricación de material de transporte.'), ('7', 'Función pública.'), ('8', 'Hotelería, restauración, turismo.'), ('9', 'otros')], max_length=1)),
                ('nombre_propietario', models.CharField(max_length=50)),
                ('numero_empleados', models.IntegerField(max_length=3)),
                ('direccion', models.TextField()),
            ],
        ),
    ]
